### ISSUE TITLE
TypeError: publicIp is not a function

### ISSUE THREAD

**Issue by ivannot** [pmenager/synology-dns-route53-updater#1]
The error is raised after installing public-ip libraries
`npm install --save public-ip`

in order to use this library I edited synoDNSUpdater.js and replaced `publicIp(publicIpCallback);` with `publicIp.v4().then(ip => {publicIpCallBack(null,ip);});`

otherwise, if you want to take advantage of error handling a different library should be used.
So `require('public-ip')` becomes `require('external-ip')` .
In this case remember to `npm install external-ip`

**Comment by shawngmc** [comment]
The problem here is that the latest version of public-ip uses Promises.

I'm about to submit a pull request that will change this, switch other calls to promises, and test the current detected IP against the current AWS record, not one stored in a file (which could lead to a non-updating condition where the file and current IP match so no action is taken even though the Route53 record is wrong).

**Comment by pmenager** [comment]
Solved in #2 thanks to @shawngmc.
